# Generated by Django 5.0.4 on 2024-09-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmSolSystem', '0002_user_celular_user_cpf_user_is_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condominio',
            name='token',
            field=models.CharField(default='pbkdf2_sha256$720000$VZ7i8YttfB5rTmWOznwOpr$7ibOjr0sbsHbxgmOOkDVaVovCuaKND4VoXrNTyf9Cis=', max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
