# Generated by Django 5.0.4 on 2024-10-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmSolSystem', '0003_alter_condominio_token_alter_user_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(blank=True, max_length=1024)),
                ('image_url', models.CharField(default='no image', max_length=1024)),
                ('quantity', models.IntegerField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='condominio',
            name='token',
            field=models.CharField(default='pbkdf2_sha256$720000$IxrVUKuZDJTyxKVmkK5DHm$3heDDxTBZcqADuuiUNj03t2xBfpEV3odwrN4/RtpacU=', max_length=128),
        ),
    ]
